version: "3.8"

services:
    icmr-entity-mapper:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8050:8050"
        volumes:
            - .:/app
        environment:
            - PYTHONUNBUFFERED=1
